# fly.toml app configuration file generated for benef-reactivities on 2023-05-16T21:14:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "benef-reactivities"
primary_region = "waw"

[build]
  image = "94102211336/reactivities2:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "162728268535247"
  Cloudinary__CloudName = "dqfdtif0q"
  Facebook__AppId ="782274383401233"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0